### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by yafjama22** [reqnroll/Reqnroll#264]
### Type of the problem

Missing information

### Problem Description

I'm not sure if this is the correct place to submit a question with a request.

I'm working on creating a plugin and have no idea which interface to use. I have successfully created a decorator plugin for IGeneratorPlugin due to the documentation.

However, I want to now make another decorator that replaces the generated nunit [TestCaseAttribute] attribute. There is no docs on which interface would do this. The properties within the interfaces are not commented either which is hard to understand what they do.

For example, ITestMethodTagDecorator.cs has a property called "Priority" that I have no idea what it means.

I guess my question is for nunit, how would one replace the generate [TestCaseAttribute] with another type of attribute?

I can add more if needed.

**Comment by gasparnagy** [comment]
I think such questions should generally go to the Q&A part of our discussion group: https://github.com/orgs/reqnroll/discussions/categories/q-a and we should only use the "Issue" if there is something wrong or obviously missing from the documentation. You can do so many things with plugins that I don't think we should (or could) document every possibility - but we can help through the Q&A and you can also check the source code about the usage.

For your concrete question:

It seems there is no direct extension point currently to replace the `[TestCaseAttribute]`. This is mainly because the values you provide there might be in sync with the other parts of the generated code (ie the method parameters). 

If you wish to replace that, what you would need to implement the full `IUnitTestGeneratorProvider` (probably by subclassing or wrapping the `NUnit3TestGeneratorProvider`) and implement a custom `SetRow` method. This new class should be registered as 

```
container.RegisterTypeAs<YourNewClass, IUnitTestGeneratorProvider>("nunit");
```

(The `Priority` field in the decorator is to control the priority of the decorators to be used if you have multiple of them.)

I close this issue here, if you have further questions to this, please add a topic in the Q&A section and I can help.
