### ISSUE TITLE
Visual Studio 2022 extension "Add New Project" adds dependency for Reqnroll.MsTest 1.0.0

### ISSUE THREAD

**Issue by noptools** [reqnroll/Reqnroll#300]
### Reqnroll Version

2.1.1 (expected)

### Which test runner are you using?

MSTest

### Test Runner Version Number

NA

### .NET Implementation

.NET 8.0

### Test Execution Method

Visual Studio Test Explorer

### Issue Description

"Add New Project" adds dependency for Reqnroll.MsTest 1.0.0 rather than (latest) 2.1.1

### Steps to Reproduce

VisualStudio 2022 17.8.0

Install the Reqnroll for Visual Studio 2022 extension by following:
[https://docs.reqnroll.net/latest/installation/setup-ide.html#setup-vs](https://docs.reqnroll.net/latest/installation/setup-ide.html#setup-vs)

The extension shows version
 v2024.4.154 - 2024-09-18

"Add New Project" > ReqnRoll
.NET 8.0
MSTest

The Dependency in the project shows as
Reqnroll.MsTest **1.0.0**
Rather than (current as of today)
Reqnroll.MsTest 2.1.1

**Comment by clrudolphi** [comment]
With the last release of the VisualStudio extension, the ProjectTemplate.csproj in folder Reqnroll.VisualStudio.ProjectTemplate, had values updated for Reqnroll.Nunit and xUnit, but not for MsTest.
```
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.10.0" />$if$ ('$unittestframework$' == 'xUnit')
    <PackageReference Include="Reqnroll.xUnit" Version="2.0.2" />
    <PackageReference Include="xunit" Version="2.8.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.1" />$endif$$if$ ('$unittestframework$' == 'NUnit')
    <PackageReference Include="Reqnroll.NUnit" Version="2.0.2" />
    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />$endif$$if$ ('$unittestframework$' == 'MSTest')
    <PackageReference Include="Reqnroll.MsTest" Version="1.0.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.4.3" />
    <PackageReference Include="MSTest.TestFramework" Version="3.4.3" />$endif$$if$ ('$fluentassertionsincluded$' == 'True')
    <PackageReference Include="FluentAssertions" Version="6.12.0" />$endif$
``` 

@gasparnagy Does it make sense to fix and re-release now or wait until the next release of Reqnroll (since you may want to update them all again anyway)?

**Comment by noptools** [comment]
Can you consider get _latest version_ of a dependency using floating version?  E.g.    Version="2.\*" or even Version="\*"?

**Comment by clrudolphi** [comment]
PR submitted: https://github.com/reqnroll/Reqnroll.VisualStudio/pull/41

**Comment by gasparnagy** [comment]
Copying my PR comment here as well:

This would make an easy fix to avoid always updating the template, but this would generate project files with the `*` style dependencies, that are pretty unsafe (and it also might confuse the VS extension, because I could not decide which Reqnroll version it is - causing problems and obscure our telemetry).

So I would not do that.

**Comment by gasparnagy** [comment]
fixed by https://github.com/reqnroll/Reqnroll.VisualStudio/pull/41
