### ISSUE TITLE
Cucumber expression errors after Specflow project migration

### ISSUE THREAD

**Issue by orifn1** [reqnroll/Reqnroll#69]
### Reqnroll Version

1.0.1

### Which test runner are you using?

MSTest

### Test Runner Version Number

3.0.2

### .NET Implementation

.NET 7.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file

{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",

  "trace": {
    "stepDefinitionSkeletonStyle": "RegexAttribute"
  }
}

### Issue Description

I am trying to migrate the existing Specflow project to Reqnroll
The project has a lot of steps in regex style but does not have specflow.json configuration file
I added reqnroll.json to the project 
```
dotnet new install Reqnroll.Templates.DotNet
dotnet new reqnroll-config
```
but it does not solve the problem
![image](https://github.com/reqnroll/Reqnroll/assets/6146067/03a19902-f284-4019-a3e0-5007f5937785)
**could you help me, I do not want to replace regex in all steps manually**

### Steps to Reproduce

just migration from Specflow to Reqnroll

**Comment by gasparnagy** [comment]
The `trace/stepDefinitionSkeletonStyle` setting is only used to provide step definition snippets (skeletons) for new steps it does not change the processing or the behavior of the existing step definitions.

I think in your case the problem is that Reqnroll (actually SpecFlow v4-beta) is detecting your step definition expressions wrongly as "cucumber expressions" although they should be treated as regular expressions.

You can always force these expressions to be handled as regex by wrapping them with `^` and `$` as described [here](https://docs.reqnroll.net/latest/guides/migrating-from-specflow.html#cucumber-expressions-support-compatibility-of-existing-expressions).

Could you please list a few of these expressions to help us better understanding why it detects them as cucumber expression?

**Comment by orifn1** [comment]
`In case your regular expression is wrongly detected as cucumber expression, you can always force to use regular expression by specifying the regex start/end markers (^/$)`

looks like this approach works but it requires a lot of manual work((

**Comment by orifn1** [comment]
Thanks it works

**Comment by orifn1** [comment]
Thanks, it works
