### ISSUE TITLE
Tests do not pass locally

### ISSUE THREAD

**Issue by Tiberriver256** [reqnroll/Reqnroll#76]
## Mega Issue

> ℹ️ **What is a 'Mega Issue'**
> This issue is set up to track several sub-issues targeted at solving the same more significant issue.

Attempting to run tests locally results in failures.

These failures may be due to:
1. An improper local setup
2. Broken functionality
3. Broken tests

Regardless of why the tests are failing locally, we'll want to solve the problem to allow making contributions easier

### Steps to Reproduce

1. Clone the repo
2. Attempt to run tests using `dotnet test` or Visual Studio Test Explorer

### Proposed General Strategy

1. Get all tests passing and running in the CI build - so that once they are passing, we can keep them passing
2. Address local testing issues for `dotnet test` - The theory being if we can get that working it will enable most development scenarios
3. Address any remaining local testing issues for Visual Studio Test Explorer
4. Address any remaining local testing issues for Rider

### Sub Issues

\#TODO

**Comment by Tiberriver256** [comment]
@reqnroll/core-team 

## Questions
1. Does this seem like a good strategy to tackle this large problem?
2. Do you think these look like good sub-issues for step 1?
   1. Add .NET Framework 4.6.2 tests to CI build
   2. Add .NET 8.0 tests to CI Build
   3. Add .NET Core 3.1 tests to CI Build

**Comment by gasparnagy** [comment]
@Tiberriver256 Thank you for taking care of this. My suggestion is that you focus your efforts to ALL tests, except the "Specs" project. The "specs" project is special and it runs end-to-end test in various different configurations, so running all of them is nearly impossible. I have some ideas how to address that, but let's separate it from this issue.

I will summarize my imagined test strategy on the discussion in detail, but in short: I would like to have a separate "system test" suite that runs end-to-end tests (with different test runners, .NET frameworks, etc.) and all other should be unit & integration test that should not need to run on multiple frameworks. 

Therefore, I suggest to change all tests (except "specs") to .NET 6.0. (We will upgrade them to .NET 8.0 once Reqnroll core is also updated.)

I *think* many of the tests fail currently because of "Broken tests", so I suggest to alter the strategy as the following (basically swapping step 1 and step 2):

0. Change test projects (except specs) to .NET 6.0
1. Address local testing issues for dotnet test (except "specs") - The theory being if we can get that working it will enable most development scenarios
2. Get all tests passing and running in the CI build (keep "specs" as separate jobs for now) - so that once they are passing, we can keep them passing
3. Address any remaining local testing issues for Visual Studio Test Explorer
4. Address any remaining local testing issues for Rider

**Comment by Code-Grump** [comment]
Solution Views might be a good way to exclude the spec projects. It's nice having the default experience be one where everything builds and runs.

**Comment by gasparnagy** [comment]
I think this issue is mostly covered by #105. Let's close it now and we might create specific issues if there are problems still.
